### ISSUE TITLE
crash on closing parenthesis after autolink

### ISSUE THREAD

**Issue by ChristianMurphy** [micromark/micromark-extension-gfm-autolink-literal#1]
### Subject of the issue

Parser crashes when there is a closing parenthesis after autolink

### Your environment

*   **OS**:  Ubuntu
*   **Packages**:
     ```
     ├── micromark-extension-gfm@0.3.2
     └── micromark@2.11.2
     ```
*   **Env**:  Node `v15.2.1`, npm `7.0.8`

### Steps to reproduce

```js
const micromark = require("micromark/lib");
const gfmSyntax = require("micromark-extension-gfm");

micromark("www.a.)", "utf-8", { extensions: [gfmSyntax()] });
```

### Expected behavior

Text should display as

www.a.)

### Actual behavior

```
AssertionError [ERR_ASSERTION]: expected non-empty token (`literalAutolinkWwwPath`)
```

**Comment by wooorm** [comment]
www.a.)

^--- well wtf, GH...
