### ISSUE TITLE
remark GFM does not parse URLs end with `_` properly

### ISSUE THREAD

**Issue by fourdim** [micromark/micromark-extension-gfm-autolink-literal#11]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-gfm@4.0.0

### Link to runnable example

https://stackblitz.com/edit/github-cbrfbi?file=src%2Fmain.ts

### Steps to reproduce

Let remark GFM parse following markdown:
```
https://example.com/MuawcBMT1Mzvoar09-_66?mode=page&blockIds=rL2_GXbtLU2SsJVfCSmh_
```

### Expected behavior

URL should be parsed to
```
<https://example.com/MuawcBMT1Mzvoar09-_66?mode=page&blockIds=rL2_GXbtLU2SsJVfCSmh_>
```

### Actual behavior

URL is parsed to 
```
<https://example.com/MuawcBMT1Mzvoar09-_66?mode=page&blockIds=rL2_GXbtLU2SsJVfCSmh>\_
```

### Runtime

Node v16

### Package manager

pnpm

### OS

Linux

### Build and bundle tools

Vite

**Comment by ChristianMurphy** [comment]
Welcome @fourdim! 👋 

That is the expected behavior.
This library matches GitHub, GitHub doesn't include the underscore.
See your example as parsed on GitHub below. 

https://example.com/MuawcBMT1Mzvoar09-_66?mode=page&blockIds=rL2_GXbtLU2SsJVfCSmh_
