### ISSUE TITLE
Parser crashes when there is a backspace control character in autolink domain

### ISSUE THREAD

**Issue by ChristianMurphy** [micromark/micromark-extension-gfm-autolink-literal#2]
### Subject of the issue

Parser crashes when there is a backspace control character in autolink

### Your environment

*   **OS**:  Ubuntu
*   **Packages**:
     ```
     ├── micromark-extension-gfm@0.3.2
     ├── micromark-extension-gfm-autolink-literal@0.5.3
     └── micromark@2.11.2
     ```
*   **Env**:  Node `v15.2.1`, npm `7.0.8`

### Steps to reproduce

```js
const micromark = require("micromark/lib");
const gfmSyntax = require("micromark-extension-gfm");

micromark("www.a", "utf-8", { extensions: [gfmSyntax()] });
```

### Expected behavior

Text should display as

www.a

### Actual behavior

```
expected non-empty token (`literalAutolinkDomain`)
```

**Comment by wooorm** [comment]
This seems to be about the actual replacement character, not about the c0 character? (as I get the error on the replacement character) 🤔

**Comment by wooorm** [comment]
OK, I can fix it, but uhm: `www.點看.com` is www.點看.com here.

Whereas the spec says:

> A valid domain consists of segments of **alphanumeric** characters, underscores (_) and hyphens (-) separated by periods (`.`)....

alphanumeric is typically a-zA-Z0-9 in markdown. But... What does GitHub allow? 🤔

**Comment by wooorm** [comment]
And more importantly, what should this extension?

**Comment by wooorm** [comment]
micromark includes info on all [`unicode-whitespace`](https://github.com/micromark/micromark/blob/main/lib/character/unicode-whitespace.mjs) and [`unicode-punctuation`](https://github.com/micromark/micromark/blob/main/lib/character/unicode-punctuation.mjs). What if we allow all other characters?

**Comment by wooorm** [comment]
(except control characters ofc)

**Comment by wooorm** [comment]
# wwwtf?

www. (space)

www.!

www."

www.#

www.$

www.%

www.&

www.'

www.(

www.)

www.*

www.+

www.,

www.-

www.

www..

www./

www.:

www.l

www.<

www.=

www.>

www.?

www.@

www.[

www.\

www.]

www.^

www._

www.`

www.{

www.|

www.}

www.~

**Comment by wooorm** [comment]
# wwwtf 2?

www.a (space)

www.a!

www.a"

www.a#

www.a$

www.a%

www.a&

www.a'

www.a(

www.a)

www.a*

www.a+

www.a,

www.a-

www.a

www.a.

www.a/

www.a:

www.al

www.a<

www.a=

www.a>

www.a?

www.a@

www.a[

www.a\

www.a]

www.a^

www.a_

www.a`

www.a{

www.a|

www.a}

www.a~

**Comment by wooorm** [comment]
well, that was complex.
