### ISSUE TITLE
Escaped characters within a URL should be treated as literals

### ISSUE THREAD

**Issue by robfig** [micromark/micromark-extension-gfm-autolink-literal#9]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Latest

### Steps to reproduce

```
import {micromark} from 'micromark'
import {
  gfmAutolinkLiteral,
  gfmAutolinkLiteralHtml
} from 'micromark-extension-gfm-autolink-literal'

const output = micromark('Just a URL: www.example.com/help\\_me .', {
  extensions: [gfmAutolinkLiteral()],
  htmlExtensions: [gfmAutolinkLiteralHtml()]
})

console.log(output)
```

I maintain a rich-text editor that stores content in Markdown. Literal underscores are escaped so that they are not interpreted. Markdown is the storage format, but the user is not typing markdown and they should not have to escape markdown special characters.  The result is that underscores within a URL are escaped. 

I believe there are two options:
* The autolinker should operate the same whether punctuation in the URL is escaped or not. 
* I would need to identify spans of text that will be auto-linked and disable escaping within them.

The second option seems pretty difficult to me. I don't see other options. 

The first option seems reasonable even for use cases other than my own -- the autolinker is used at display-time, yet it places restrictions on the way users author their markdown. That dependency seems undesirable.

### Expected behavior

```
<p>Just a URL: <a href="http://www.example.com/help_me">www.example.com/help_me</a> .</p>
```

### Actual behavior

```
<p>Just a URL: <a href="http://www.example.com/help%5C_me">www.example.com/help\_me</a> .</p>
```

**Comment by wooorm** [comment]
That’s how they work in GH: Just a URL: www.example.com/help\_me .

**Comment by ChristianMurphy** [comment]
Welcome @robfig! 👋 
Sorry you ran into a spot of trouble.

The current behavior matches GitHub Flavored markdown

You can confirm this by taking your example
```markdown
Just a URL: www.example.com/help\\_me .
```
pasting it into GitHub

---

Just a URL: www.example.com/help\\_me .

---

and inspecting the result

```html
<a href="http://www.example.com/help%5C%5C_me" rel="nofollow">www.example.com/help\\_me</a>
```

`micromark-extension-gfm-autolink` matches the autolinking behavior to GitHub.

> I maintain a rich-text editor that stores content in Markdown. Literal underscores are escaped so that they are not interpreted. Markdown is the storage format, but the user is not typing markdown and they should not have to escape markdown special characters. The result is that underscores within a URL are escaped.

My humble suggestion is have the editor generate valid GFM.
Rather than creating yet another bespoke flavor of markdown.

**Comment by wooorm** [comment]
> Markdown is the storage format, but the user is not typing markdown and they should not have to escape markdown special characters.

So is HTML. And users needs to know how to handle things like `<` too
